"""Shared configuration: award patterns, topic keywords, NES keywords."""

# Award name patterns — single source of truth
AWARD_PATTERNS = {
    "cleaning": "Cleaning Services Award 2020",
    "cleaner": "Cleaning Services Award 2020",
    "hospitality": "Hospitality Industry (General) Award 2020",
    "hotel": "Hospitality Industry (General) Award 2020",
    "clerk": "Clerks—Private Sector Award 2010",
    "clerks": "Clerks—Private Sector Award 2010",
    "private sector clerks": "Clerks—Private Sector Award 2010",
    "payroll officer": "Clerks—Private Sector Award 2010",
    "payroll": "Clerks—Private Sector Award 2010",
    "retail": "General Retail Industry Award 2020",
    "fast food": "Fast Food Industry Award 2020",
    "restaurant": "Restaurant Industry Award 2020",
    "professional employee": "Professional Employees Award 2020",
    "software engineer": "Professional Employees Award 2020",
    "architect": "Architects Award 2020",
    "architects": "Architects Award 2020",
    "hair and beauty": "Hair and Beauty Industry Award 2020",
    "hairdresser": "Hair and Beauty Industry Award 2020",
    "marine": "Marine Tourism and Charter Vessels Award 2020",
    "charter vessel": "Marine Tourism and Charter Vessels Award 2020",
    "sporting": "Sporting Organisations Award 2020",
    "sport": "Sporting Organisations Award 2020",
    "animal care": "Animal Care and Veterinary Services Award 2020",
    "veterinary": "Animal Care and Veterinary Services Award 2020",
    "aquaculture": "Aquaculture Industry Award 2020",
    "cotton": "Cotton Ginning Award 2020",
    "black coal": "Black Coal Mining Industry Award 2020",
    "mining": "Black Coal Mining Industry Award 2020",
    "aluminium": "Aluminium Industry Award 2020",
    "steel": "Steel Industry Award 2020",
    "waste": "Waste Management Award 2020",
    "local government": "Local Government Industry Award 2020",
    "nursing": "Nursing Award 2020",
    "nurse": "Nursing Award 2020",
    "health": "Health Professionals and Support Services Award 2020",
    "hospital": "Health Professionals and Support Services Award 2020",
    "ambulance": "Ambulance Industry Award 2020",
    "education": "Educational Services (Schools) General Staff Award 2020",
    "school": "Educational Services (Schools) General Staff Award 2020",
    "child care": "Children's Services Award 2010",
    "childcare": "Children's Services Award 2010",
    "children's services": "Children's Services Award 2010",
    "aged care": "Aged Care Award 2010",
    "agedcare": "Aged Care Award 2010",
    "social and community": "Social, Community, Home Care and Disability Services Award 2020",
    "disability": "Social, Community, Home Care and Disability Services Award 2020",
    "community": "Social, Community, Home Care and Disability Services Award 2020",
    "home care": "Social, Community, Home Care and Disability Services Award 2020",
    "wages": "General minimum wage",
    "minimum wage": "General minimum wage",
    "airline": "Airline Operations—Ground Staff Award 2020",
    "airport": "Airport Employees Award 2020",
    "banking": "Banking, Finance and Insurance Award 2020",
    "finance": "Banking, Finance and Insurance Award 2020",
    "insurance": "Banking, Finance and Insurance Award 2020",
    "building": "Building and Construction General On-site Award 2020",
    "construction": "Building and Construction General On-site Award 2020",
    "electrical": "Electrical, Electronic and Communications Contracting Award 2020",
    "plumbing": "Plumbing and Fire Sprinklers Award 2020",
    "gardening": "Gardening and Landscaping Services Award 2020",
    "landscaping": "Gardening and Landscaping Services Award 2020",
    "graphic arts": "Graphic Arts, Printing and Publishing Award 2020",
    "printing": "Graphic Arts, Printing and Publishing Award 2020",
    "publishing": "Graphic Arts, Printing and Publishing Award 2020",
    "higher education": "Higher Education Industry-Academic Staff-Award 2020",
    "university": "Higher Education Industry-Academic Staff-Award 2020",
    "pharmacy": "Pharmacy Industry Award 2020",
    "telecommunications": "Telecommunications Services Award 2020",
    "truck": "Road Transport and Distribution Award 2020",
    "transport": "Road Transport and Distribution Award 2020",
    "distribution": "Road Transport and Distribution Award 2020",
    "security": "Security Services Industry Award 2020",
    "textile": "Textile, Clothing, Footwear and Associated Industries Award 2020",
    "clothing": "Textile, Clothing, Footwear and Associated Industries Award 2020",
    "footwear": "Textile, Clothing, Footwear and Associated Industries Award 2020",
    "manufacturing": "Manufacturing and Associated Industries and Occupations Award 2020",
    "warehousing": "Warehousing, Storage and Distribution Award 2020",
    "wine": "Wine Industry Award 2020",
    "sugar": "Sugar Industry Award 2020",
    "port": "Port Authorities Award 2020",
    "pilot": "Air Pilots Award 2020",
    "flight attendant": "Aircraft Cabin Crew Award 2020",
    "cabin crew": "Aircraft Cabin Crew Award 2020",
    "fitness": "Fitness Industry Award 2020",
    "gym": "Fitness Industry Award 2020",
    "funeral": "Funeral Industry Award 2020",
    "cemetery": "Cemetery Industry Award 2020",
    "broadcasting": "Broadcasting, Recorded Entertainment and Cinemas Award 2020",
    "cinema": "Broadcasting, Recorded Entertainment and Cinemas Award 2020",
    "events": "Amusement, Events and Recreation Award 2020",
    "recreation": "Amusement, Events and Recreation Award 2020",
    "amusement": "Amusement, Events and Recreation Award 2020",
    "asphalt": "Asphalt Industry Award 2020",
    "cement": "Cement, Lime and Quarrying Award 2020",
    "quarrying": "Cement, Lime and Quarrying Award 2020",
    "concrete": "Concrete Products Award 2020",
    "dredging": "Dredging Industry Award 2020",
    "dry cleaning": "Dry Cleaning and Laundry Industry Award 2020",
    "laundry": "Dry Cleaning and Laundry Industry Award 2020",
    "fire fighting": "Fire Fighting Industry Award 2020",
    "firefighter": "Fire Fighting Industry Award 2020",
    "gas": "Gas Industry Award 2020",
    "corrections": "Corrections and Detention (Private Sector) Award 2020",
    "detention": "Corrections and Detention (Private Sector) Award 2020",
    "call centre": "Contract Call Centres Award 2020",
    "call center": "Contract Call Centres Award 2020",
    "business equipment": "Business Equipment Award 2020",
    "commercial sales": "Commercial Sales Award 2020",
    "coal export": "Coal Export Terminals Award 2020",
    "book": "Book Industry Award 2020",
    "alpine": "Alpine Resorts Award 2020",
    "aboriginal": "Aboriginal and Torres Strait Islander Health Workers and Practitioners Award 2020",
    "government": "Australian Government Industry Award 2016",
    "federal government": "Australian Government Industry Award 2016",
    "power": "Electrical Power Industry Award 2020",
    "electricity": "Electrical Power Industry Award 2020",
    "post-secondary": "Educational Services (Post-Secondary Education) Award 2020",
    "tertiary": "Educational Services (Post-Secondary Education) Award 2020",
    "teachers": "Educational Services (Teachers) Award 2020",
    # DEF-013/062: Additional award aliases for better join coverage
    "car parking": "Car Parking Award 2020",
    "carpark": "Car Parking Award 2020",
    "parking": "Car Parking Award 2020",
    "state government": "State Government Agencies Award 2015",
    "government agencies": "State Government Agencies Award 2015",
    "public servants": "State Government Agencies Award 2015",
    "clerks private": "Clerks—Private Sector Award 2010",
    "coal mining": "Black Coal Mining Industry Award 2020",
    "mineral": "Mining Industry Award 2020",
    "minerals": "Mining Industry Award 2020",
    "legal": "Legal Services Award 2020",
    "lawyer": "Legal Services Award 2020",
    "solicitor": "Legal Services Award 2020",
    "meat": "Meat Industry Award 2020",
    "abattoir": "Meat Industry Award 2020",
    "poultry": "Poultry Processing Award 2020",
    "nursery": "Nursery Award 2020",
    "real estate": "Real Estate Industry Award 2020",
    "realty": "Real Estate Industry Award 2020",
    "pastoral": "Pastoral Award 2020",
    "cattle": "Pastoral Award 2020",
    "sheep": "Pastoral Award 2020",
    "horse": "Horse and Greyhound Training Award 2020",
    "greyhound": "Horse and Greyhound Training Award 2020",
    "racing": "Racing Clubs Events Award 2020",
    "race": "Racing Clubs Events Award 2020",
    "club": "Registered and Licensed Clubs Award 2020",
    "licensed club": "Registered and Licensed Clubs Award 2020",
    "rail": "Rail Industry Award 2020",
    "railway": "Rail Industry Award 2020",
    "oil": "Oil Refining and Manufacturing Award 2020",
    "refinery": "Oil Refining and Manufacturing Award 2020",
    "maritime": "Maritime Offshore Oil and Gas Award 2020",
    "offshore": "Maritime Offshore Oil and Gas Award 2020",
    "seagoing": "Seagoing Industry Award 2020",
    "stevedoring": "Stevedoring Industry Award 2020",
    "wharf": "Stevedoring Industry Award 2020",
    "surveying": "Surveying Award 2020",
    "surveyor": "Surveying Award 2020",
    "timber": "Timber Industry Award 2020",
    "wood": "Timber Industry Award 2020",
    "water": "Water Industry Award 2020",
    "silviculture": "Silviculture Award 2020",
    "tree": "Silviculture Award 2020",
    "pest control": "Pest Control Industry Award 2020",
    "vermin": "Pest Control Industry Award 2020",
    "diving": "Professional Diving Industry Industrial Award 2020",
    "sales rep": "Commercial Sales Award 2020",
    "market research": "Market and Social Research Award 2020",
    "social research": "Market and Social Research Award 2020",
    "medical practitioner": "Medical Practitioners Award 2020",
    "doctor": "Medical Practitioners Award 2020",
    "physician": "Medical Practitioners Award 2020",
    "mobile crane": "Mobile Crane Hiring Award 2020",
    "crane": "Mobile Crane Hiring Award 2020",
    "premixed concrete": "Premixed Concrete Award 2020",
    "concrete mixing": "Premixed Concrete Award 2020",
    "supported employment": "Supported Employment Services Award 2020",
    "disability supported": "Supported Employment Services Award 2020",
    "wool": "Wool Storage Sampling and Testing Award 2020",
    "salt": "Salt Industry Award 2020",
    "storage": "Storage Services and Wholesale Award 2020",
    "wholesale": "Storage Services and Wholesale Award 2020",
    "seafood": "Seafood Processing Award 2020",
    "fish": "Seafood Processing Award 2020",
    "travel": "Travelling Shows Award 2020",
    "circus": "Travelling Shows Award 2020",
    "vehicle": "Vehicle Repair Services and Retail Award 2020",
    "car repair": "Vehicle Repair Services and Retail Award 2020",
    "mechanic": "Vehicle Repair Services and Retail Award 2020",
    "cash in transit": "Transport Cash in Transit Award 2020",
    "armoured": "Transport Cash in Transit Award 2020",
    "mannequin": "Mannequins and Models Award 2020",
    "model": "Mannequins and Models Award 2020",
    "services": "Services Award 2020",
    "miscellaneous": "Miscellaneous Award 2020",
    "telstra": "Telstra Award 2015",
    "victorian government": "Victorian Government Schools Award 2016",
    "victorian local government": "Victorian Local Government Award 2015",
    "victorian public service": "Victorian Public Service Award 2016",
    "hydrocarbons": "Hydrocarbons Industry Upstream Award 2020",
    "gas field": "Hydrocarbons Field Geologists Award 2020",
    "journalist": "Journalists Published Media Award 2020",
    "media": "Journalists Published Media Award 2020",
    "food manufacturing": "Food Beverage and Tobacco Manufacturing Award 2020",
    "tobacco": "Food Beverage and Tobacco Manufacturing Award 2020",
    "live performance": "Live Performance Award 2020",
    "theatre": "Live Performance Award 2020",
    "pharmaceutical": "Pharmaceutical Industry Award 2020",
    "drug": "Pharmaceutical Industry Award 2020",
    "horticulture": "Horticulture Award 2020",
    "fruit": "Horticulture Award 2020",
    "vegetable": "Horticulture Award 2020",
    "joinery": "Joinery and Building Trades Award 2020",
    "cabinet": "Joinery and Building Trades Award 2020",
    "labour market": "Labour Market Assistance Industry Award 2020",
    "employment services": "Labour Market Assistance Industry Award 2020",
    "patient transport": "Ambulance and Patient Transport Industry Award 2020",
    "professional diving": "Professional Diving Industry Recreational Award 2020",
    "recreational diving": "Professional Diving Industry Recreational Award 2020",
    "towage": "Marine Towage Award 2020",
    "tug": "Marine Towage Award 2020",
    "harbour": "Ports Harbours and Enclosed Water Vessels Award 2020",
    "hydrocarbons field": "Hydrocarbons Field Geologists Award 2020",
    "mining industry": "Mining Industry Award 2020",
    "supported employment services": "Supported Employment Services Award 2020",
    "registered clubs": "Registered and Licensed Clubs Award 2020",
    "licensed clubs": "Registered and Licensed Clubs Award 2020",
}

# Topic keywords for general questions
TOPIC_KEYWORDS = {
    "overtime": ["overtime", "overtime rate", "overtime pay", "overtime hours", "time and a half", "double time", "overtime entitlement"],
    "penalty": ["penalty rate", "penalties", "weekend penalty", "penalty rates", "penalty loading", "sunday penalty", "saturday penalty", "public holiday penalty"],
    "break": ["meal break", "rest break", "break entitlement", "breaks", "unpaid break", "paid break", "smoko", "tea break"],
    "leave": ["leave entitlement", "annual leave", "personal leave", "sick leave", "carer's leave", "long service leave", "parental leave", "compassionate leave", "community service leave", "domestic violence leave", "family violence leave"],
    "casual": ["casual employee", "casual loading", "casual rate", "casual conversion", "casual hours", "casual engagement", "casual minimum engagement", "casual entitlements"],
    "notice": ["notice of termination", "notice period", "resignation", "termination", "summary dismissal", "final pay", "termination pay", "redundancy notice"],
    "allowance": ["allowance", "allowances", "payment", "travel allowance", "uniform allowance", "meal allowance", "tool allowance", "vehicle allowance", "housing allowance", "overtime allowance", "first aid allowance"],
    "hours": ["hours of work", "maximum hours", "weekly hours", "ordinary hours", "span of hours", "daily hours", "average hours", "flexible hours", "compressed hours", "part-time hours", "full-time hours"],
    "public holiday": ["public holiday", "public holidays", "holiday penalty", "working on a public holiday", "sunday public holiday", "additional day"],
    "weekend": ["saturday", "sunday", "weekend work", "weekend penalty", "saturday work", "sunday work", "weekend rates", "saturday rates", "sunday rates"],
    "roster": ["roster", "rostering", "roster cycle", "roster pattern", "shift roster", "duty roster", "work roster", "rostering arrangements"],
    "junior": ["junior employee", "junior rate", "under 18", "apprentice", "junior pay", "under 16", "under 17", "young worker"],
    "apprentice": ["apprentice", "apprenticeship", "trainee", "traineeship", "tradesperson", "trade qualification"],
    "wages": ["hourly rate", "minimum wage", "pay rate", "salary", "wage", "annual salary", "weekly pay", "fortnightly pay", "pay slip", "underpayment"],
    "redundancy": ["redundancy", "redundant", "redundancy pay", "redundancy consultation", "genuine redundancy", "redundancy entitlements"],
    "transfer": ["transfer", "transfer of business", "transfer of employment", "transfer of undertaking", "TUPE equivalent"],
    "unfair dismissal": ["unfair dismissal", "dismissal", "termination of employment", "harsh", "unconscionable", "without valid reason"],
    "consultation": ["consultation", "consultation requirement", "redundancy consultation", "change management", "workplace change"],
    "record keeping": ["record", "time and wages", "pay slip", "record keeping", "time sheet", "timesheet", "work diary", "attendance record"],
    # DEF-065: Additional common phrasings
    "leave loading": ["leave loading", "annual leave loading", "loading on leave"],
    "superannuation": ["superannuation", "super", "super guarantee", "SG", "retirement savings"],
    "workers compensation": ["workers compensation", "workcover", "workplace injury", "injury at work", "occupational health"],
    "whistleblower": ["whistleblower", "whistle blowing", "reporting misconduct", "public interest disclosure"],
    "discrimination": ["discrimination", "equal pay", "gender pay", "pay equity", "fair pay", "equal remuneration"],
    "harassment": ["harassment", "bullying", "sexual harassment", "workplace bullying", "victimisation"],
    "stand down": ["stand down", "stood down", "stand-down period", "direction to stand down"],
    "secondment": ["secondment", "seconded", "temporary transfer", "acting arrangement", "higher duties"],
    "abandonment": ["abandonment", "abandoned employment", "absence from work", "unexplained absence"],
    "training": ["training", "training leave", "study leave", "training arrangement", "structured training", "on-the-job training"],
    "work from home": ["work from home", "working from home", "remote work", "telecommuting", "flexible work arrangement", "work arrangement"],
    "split shift": ["split shift", "broken shift", "split roster", "broken roster"],
    "on call": ["on-call", "on call", "on-call allowance", "standby", "availability"],
    "travel time": ["travel time", "travel allowance", "travelling time", "commute", "journey to work"],
    "tools": ["tools of trade", "tool allowance", "tool reimbursement", "provision of tools", "personal protective equipment", "PPE", "safety equipment"],
    "uniform": ["uniform", "uniform allowance", "dress code", "protective clothing", "work clothing"],
    "first aid": ["first aid", "first aid allowance", "first aid certificate", "first aid officer"],
    "lactation": ["lactation", "breastfeeding", "nursing room", "lactation break"],
    "jury duty": ["jury duty", "jury service", "jury leave", "jury allowance"],
    "voting": ["voting", "time to vote", "polling day", "election day"],
}

# NES keywords — questions about these always use CAG or Combined
NES_KEYWORDS = [
    "nes", "national employment standards",
    "leave entitlement", "annual leave", "personal leave",
    "parental leave", "notice of termination", "redundancy",
    "public holiday", "maximum weekly hours", "flexible working",
    "casual employment", "community service leave", "long service leave",
    "superannuation",
    # DEF-018: Additional NES items from requirements
    "family and domestic violence leave",
    "domestic violence", "family violence",
    "national employment standard",
    "NES entitlement", "NES entitlements",
    "10 entitlements", "ten entitlements",
    "notice period", "redundancy pay",
    "fair work information statement", "FWIS",
    "casual employment information statement", "CEIS",
    "new employee", "starting work",
    "unpaid parental leave", "paid parental leave",
    "special national employer contribution", "SNEC",
    "no safe job parental leave",
    "extension of parental leave",
    "return to work from parental leave",
    "keeper of time", "time and wages records",
    "annualised salary", "annualised wage",
    "set-off", "set off", "set-off provisions",
    "absent from work", "absence from work",
    "public services", "state government employee",
    "Australian government employee",
    "federal employee", "government employee",
    "casual conversion", "conversion to permanent",
    "offer of conversion", "refusal of conversion",
    "minimum engagement", "minimum period of employment",
    "probation period", "probationary period",
    "workplace health and safety", "OHS", "WHS",
    "workplace relations", "Fair Work Act",
    "modern award", "enterprise agreement",
    "national minimum wage", "minimum wage order",
    "annual wage review", "wage increase",
    "casual loading", "casual entitlement",
    "part-time entitlement", "full-time entitlement",
    "shift work", "shift loading",
    "weekend work", "public holiday work",
    "overtime entitlement", "overtime rate",
    "penalty rate entitlement", "penalty loading",
    "leave loading", "leave entitlement",
    "compassionate leave", "carer's leave",
    "bereavement leave", "death in service",
    "jury service", "jury duty",
    "voting entitlement", "time to vote",
    "training leave", "study leave",
    "domestic violence leave",
    "family and domestic violence",
    "10 national employment standards",
    "NES provisions", "NES clauses",
    "Part 2-2", "Part 2-3", "Part 2-4", "Part 2-5", "Part 2-6",
    "Part 3-1", "Part 3-2", "Part 3-3", "Part 3-4", "Part 3-5",
    "Part 3-6",
]


def detect_award(question: str):
    """Detect award name from question text. Returns award name or None."""
    q = question.lower()
    for keyword, award_name in AWARD_PATTERNS.items():
        if keyword in q:
            return award_name
    return None


def detect_topic(question: str):
    """Detect topic from question text. Returns topic name or None."""
    q = question.lower()
    for topic, keywords in TOPIC_KEYWORDS.items():
        if any(kw in q for kw in keywords):
            return topic
    return None


def has_nes_keywords(question: str) -> bool:
    """Check if question mentions NES-related content."""
    q = question.lower()
    return any(kw in q for kw in NES_KEYWORDS)
